### ISSUE TITLE
Dependencies not making it to markdown

### ISSUE THREAD

**Issue by WillBeebe** [jaketf/jsonschema2md#3]
Hello awesome library maintainer 👋 . 

I'm started to get into more complicated json schema with `dependencies` and was hoping this tool could help me document them! With the below yaml, only the `enable_cluster` is making it to the docs, not `shard_count`.

```
params:
  properties:
    enable_cluster:
      type: boolean
      title: Redis clustering
      default: false
  required:
    - enable_cluster
  dependencies:
    enable_cluster:
      oneOf:
        - properties:
            enable_cluster:
              enum:
                - true
            shard_count:
              type: integer
              title: Redis cluster shard count
              default: 1
              enum:
                - 1
                - 2
                - 3
                - 4
                - 5
        - properties:
             enable_cluster:
               enum:
                 - false        
```
